Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        FEATURE_FLAG_TABLE_NAME: Your feature flag table name
        AWS_REGION: Your aws region
        AWS_ACCESS_KEY: Your aws access key
        AWS_SECRET_KEY: Your aws secret key
        FEATURE_FLAG_USER_MAPPING_TABLE_NAME: Your feature flag user mapping table name
        ENVIRONMENT: PRODUCTION

Resources:
  HealthCheckFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: health-check/
      Handler: health-check
      Runtime: go1.x
      Architectures:
        - x86_64  
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /health-check
            Method: GET
  GetFeatureFlagFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: getFeatureFlagById/
      Handler: getFeatureFlagById
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties: 
            Path: /feature-flags/{flagId}
            Method: GET 